election_timeout = { minimum_ms = 300, maximum_ms = 500 }

members = [
  { id = "node1", raft_addr = "127.0.0.1:9001", client_addr = "127.0.0.1:8081" },
  { id = "node2", raft_addr = "127.0.0.1:9002", client_addr = "127.0.0.1:8082" },
  { id = "node3", raft_addr = "127.0.0.1:9003", client_addr = "127.0.0.1:8083" }
]